services:
  server-dev:
    profiles: ['dev']
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=development
    command: ['pnpm', '--filter', 'server', 'dev']

  server-prod:
    profiles: ['prod']
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
