services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - '${SERVER_PORT:-3000}:3000'
    networks:
      - vera_network

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    networks:
      - vera_network
    environment:
      - SERVER_PORT=${SERVER_PORT:-3000}
      - SERVER_ADDRESS=${SERVER_ADDRESS:-localhost}

  elastic-search:
    image: elasticsearch:9.1.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-credentials=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    networks:
      - vera_network

  elastic-initializer:
    build:
      context: .
      dockerfile: packages/elastic-initializer/Dockerfile
      target: dev
    depends_on:
      - elastic-search
    environment:
      - ELASTIC_NODE=${ELASTIC_NODE:-http://elastic-search:9200}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
    volumes:
      - ./packages/elastic-initializer/src:/app/packages/elastic-initializer/src
    networks:
      - vera_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_NODE:-http://elastic-search:9200}
    ports:
      - 5601:5601
    networks:
      - vera_network

networks:
  vera_network:

volumes:
  esdata:
