services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - "${SERVER_PORT:-3000}:3000"

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile

  elastic-search:
    image: elasticsearch:9.1.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-credentials=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
      

  elastic-initializer:
    build: 
      context: .
      dockerfile: packages/elastic-initializer/Dockerfile
      target: dev
    depends_on:
      - elastic-search
    environment:
      - ELASTIC_NODE=http://elastic-search:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./packages/elastic-initializer/src:/app/packages/elastic-initializer/src

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=http://elastic-search:9200
    ports:
      - 5601:5601

volumes:
  esdata: