services:
  server:
    build:
      target: dev
    environment:
      - NODE_ENV=development
    volumes:
      - ./packages/server/src:/app/packages/server/src:z
  frontend:
    build:
      target: dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    ports:
      - '${FRONTEND_PORT:-3001}:3001'
    volumes:
      - ./packages/frontend/src:/app/packages/frontend/src:z

  elastic-search:
    volumes:
      - esdata:/usr/share/elasticsearch/data

  elastic-initializer:

  kibana:

  postgres:

  adminer:
