services:
  server:
    restart: 'on-failure:10'
    build:
      target: runtime
    environment:
      - NODE_ENV=production

  frontend:
    build:
      target: runtime
    environment:
      - NODE_ENV=production
    ports:
      - '${FRONTEND_PORT:-3001}:80'

  elastic-search:
    volumes:
      - esdata:/usr/share/elasticsearch/data

  elastic-initializer:

  kibana:

  postgres:

  adminer:

#volumes:
#  esdata:
