services:
  server:
    build:
      context: .
      dockerfile: packages/server/Dockerfile
    ports:
      - '${SERVER_PORT:-3000}:3000'
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - SERVER_ALLOWED_ORIGIN=${FRONTEND_ADDRESS:-localhost:3001}
    networks:
      - vera_network
    labels:
      - traefik.enable=true

      - traefik.http.routers.server.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls.certresolver=le

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    networks:
      - vera_network
    environment:
      - VITE_SERVER_ADDRESS=${SERVER_ADDRESS:-localhost:3000}
      - VITE_FRONTEND_ADDRESS=${FRONTEND_ADDRESS:-localhost:3001}
    labels:
      - traefik.enable=true

      - traefik.http.routers.frontend.rule=Host(`${FRONTEND_ADDRESS}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=le

  elastic-search:
    image: elasticsearch:9.1.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-credentials=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    networks:
      - vera_network

  initializer:
    build:
      context: .
      dockerfile: packages/initializer/Dockerfile
      target: dev
    depends_on:
      - elastic-search
    environment:
      - ELASTIC_NODE=${ELASTIC_NODE:-http://elastic-search:9200}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
    volumes:
      - ./packages/initializer/src:/app/packages/initializer/src:z
    networks:
      - vera_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_NODE:-http://elastic-search:9200}
    ports:
      - 5601:5601
    networks:
      - vera_network

  postgres:
    image: postgres:18
    volumes:
      - postgresdata:/var/lib/postgresql/18/docker:z
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-pass}'
      POSTGRES_PORT: '${POSTGRES_PORT:-5432}'
      POSTGRES_DB: '${POSTGRES_DB:-vera}'

    ports:
      - 5432:5432
    networks:
      - vera_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    networks:
      - vera_network

networks:
  vera_network:

volumes:
  esdata:
  postgresdata:
