services:
  server:
    restart: 'on-failure:10'
    build:
      target: runtime
    environment:
      - NODE_ENV=production
      - ELASTIC_PASSWORD="${ELASTIC_PASSWORD:-pass}"
    profiles: ['prod']

  frontend:
    build:
      target: runtime
    environment:
      - NODE_ENV=production
    ports:
      - '${FRONTEND_PORT:-3001}:80'
    profiles: ['prod']

  elastic-search:
    volumes:
      - esdata:/usr/share/elasticsearch/data

  elastic-initializer:

  kibana:

#volumes:
#  esdata:
