services:
  server:
    image: 'ghcr.io/patrikprinz/vera-server:latest'
    ports:
      - '${SERVER_PORT:-3000}:3000'
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
      - SERVER_ALLOWED_ORIGIN=${FRONTEND_ADDRESS:-localhost:3001}
    networks:
      - vera_network
    labels:
      - traefik.enable=true

      - traefik.http.routers.server.rule=Host(`${SERVER_ADDRESS}`)
      - traefik.http.routers.server.entrypoints=websecure
      - traefik.http.routers.server.tls.certresolver=le

  frontend:
    image: 'ghcr.io/patrikprinz/vera-frontend:latest'
    networks:
      - vera_network
    environment:
      - VITE_SERVER_ADDRESS=${SERVER_ADDRESS:-localhost:3000}
      - VITE_FRONTEND_ADDRESS=${FRONTEND_ADDRESS:-localhost:3001}
    ports:
      - '${FRONTEND_PORT:-3001}:80'
    labels:
      - traefik.enable=true

      - traefik.http.routers.frontend.rule=Host(`${FRONTEND_ADDRESS}`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=le

  elastic-search:
    image: elasticsearch:9.1.2
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://localhost:3000
      - http.cors.allow-credentials=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - 9200:9200
    networks:
      - vera_network
    volumes:
      - esdata:/usr/share/elasticsearch/data

  initializer:
    image: 'ghcr.io/patrikprinz/vera-initializer:latest'
    depends_on:
      - elastic-search
    environment:
      - ELASTIC_NODE=${ELASTIC_NODE:-http://elastic-search:9200}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME:-elastic}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pass}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-pass}
    networks:
      - vera_network

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.5
    #volumes:
    #- ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elastic-search
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTIC_NODE:-http://elastic-search:9200}
    ports:
      - 5601:5601
    networks:
      - vera_network

networks:
  vera_network:

volumes:
  esdata:
