name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['dev', 'master']

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          standalone: true
      - run: pnpm -v
      - run: pnpm install --frozen-lockfile
      - name: ESLint
        run: pnpm ci:lint
      - name: Prettier check
        run: pnpm ci:format
      - name: Run tests
        run: pnpm test:unit
